### PR TITLE
start frontend

### PR DESCRIPTION
**Pull request by elianiva**
biar ngga lupa

### CODE REVIEW

**Comment by aldy505** [comment]
yaelah repo kuis aja lupa WKWKKWWK

**Comment by elianiva** [comment]
WKWKWK
bukan lupa, ngestuck

**Comment by aldy505** [comment]
https://user-images.githubusercontent.com/7274326/130362592-d9dcf907-1e6c-4fed-a48c-06c348b9ae44.mp4

@elianiva situ tinggal ngerjain styling. buat yang language auto, kayaknya next release flourite bakal aku bikin versi UMD deh, biar bisa dipake langsung di browser.

**Comment by aldy505** [comment]
ok should we close this one?

**Comment by elianiva** [comment]
image

**Pull request closed without merging**
