### PR TITLE
🐴

### PR DESCRIPTION
**Pull request by elianiva**
implement proper border without bg hack + proper upscale logic (no longer blurry)

image

### CODE REVIEW

**Comment by elianiva** [comment]
sebenernya kodenya bisa disimplify lagi, tapi ngga bisa pake rounded corner

<details>
<summary>
Code
</summary>

```diff
diff --git a/src/handler/core.ts b/src/handler/core.ts
index f70ff22..3ad02ba 100644
--- a/src/handler/core.ts
+++ b/src/handler/core.ts
@@ -51,25 +51,7 @@ export const coreHandler: Middleware = async (req, res) => {
       size: 20,
       colour: { r: 160, g: 173, b: 182, alpha: 1 },
     };
-    const codeFrame = sharp(Buffer.from(svg), { density: 72 * upscale });
-    const codeFrameMeta = await codeFrame.metadata();
-
-    // Convert the SVG to PNG
-    const codeImage = await sharp({
-      create: {
-        // Create Transparent Background
-        width: codeFrameMeta.width as number,
-        height: codeFrameMeta.height as number,
-        channels: 4,
-        background: border.colour,
-      },
-    })
-      .composite([
-        {
-          // Draw the SVG in front of the background
-          input: await codeFrame.toBuffer(),
-        },
-      ])
+    const codeImage = await sharp(Buffer.from(svg), { density: 72 * upscale })
       .extend({
         left: border.size,
         right: border.size,
```

</details>

image

**Comment by aldy505** [comment]
@elianiva conflict

**Comment by aldy505** [comment]
and uh, would you consider changing the PR name to be appropriate? it should be an emoji.

thank you

lmao

**Comment by elianiva** [comment]
@aldy505 kalo ngga ada review lagi, merge aja ini, aku udah selesai

**Review by aldy505 — APPROVED** [review]

**Pull request merged**
